### ISSUE TITLE
VipsOperation: class "pdfload" not found error arises while converting pdf

### ISSUE THREAD

**Issue by akashkinwad** [riboseinc/despeck#18]
Using despeck remove for the pdf, it is giving error for the VipsOperation: class "pdfload" not found

Used through terminal line as below

`despeck remove --color 999999 --sensitivity 120 --black-const -60 --add-contrast '/home/Desktop/Doc-Test-3.pdf' '/home/dl64/Desktop/output_44.pdf'
`
error log is as below

```
  18: from /home/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
  17: from /home/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
  16: from /home/.rvm/gems/ruby-2.5.3/bin/despeck:23:in `<main>'
  15: from /home/.rvm/gems/ruby-2.5.3/bin/despeck:23:in `load'
  14: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/bin/despeck:8:in `<top (required)>'
  13: from /home/.rvm/gems/ruby-2.5.3/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
  12: from /home/.rvm/gems/ruby-2.5.3/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
  11: from /home/.rvm/gems/ruby-2.5.3/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
  10: from /home/.rvm/gems/ruby-2.5.3/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
   9: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/commands/remove.rb:46:in `execute'
   8: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:12:in `pdf_to_images'
   7: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:39:in `for_each_page'
   6: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:39:in `times'
   5: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:40:in `block in for_each_page'
   4: from /home/.rvm/gems/ruby-2.5.3/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:13:in `block in pdf_to_images'
   3: from /home/.rvm/gems/ruby-2.5.3/gems/ruby-vips-2.0.13/lib/vips/image.rb:215:in `method_missing'
   2: from /home/.rvm/gems/ruby-2.5.3/gems/ruby-vips-2.0.13/lib/vips/operation.rb:232:in `call'
   1: from /home/.rvm/gems/ruby-2.5.3/gems/ruby-vips-2.0.13/lib/vips/operation.rb:232:in `new'
/home/.rvm/gems/ruby-2.5.3/gems/ruby-vips-2.0.13/lib/vips/operation.rb:65:in `initialize': VipsOperation: class "pdfload" not found (Vips::Error)
```

Thanks

**Comment by ronaldtse** [comment]
@akashkinwad thanks for the report. I believe `pdfload` is a command from `libvips`, which is a dependency. Perhaps it is the version of `ruby-vips` that is problematic (then we will need better version dependencies).

@nattfodd could you help look at this? Thanks!

**Comment by blackpond** [comment]
Did you find a solution to this?  I'm also getting the same error:

```
Vips::Error (VipsOperation: class "pdfload" not found
):
F, [2019-08-26T08:47:48.769982 #14323] FATAL -- : [a5ff3770-c1f3-4ce5-a762-1a3759efa28f]   
F, [2019-08-26T08:47:48.770087 #14323] FATAL -- : [a5ff3770-c1f3-4ce5-a762-1a3759efa28f] app/uploaders/pdf_package_uploader.rb:94:in `convert_to_images'
[a5ff3770-c1f3-4ce5-a762-1a3759efa28f] app/models/pdf_package.rb:13:in `recreate_delayed_versions!'
[a5ff3770-c1f3-4ce5-a762-1a3759efa28f] app/models/pdf_package.rb:17:in `process_images'
[a5ff3770-c1f3-4ce5-a762-1a3759efa28f] app/controllers/pdf_packages_controller.rb:101:in `create'
```

**Comment by ronaldtse** [comment]
@blackpond thanks for the report. Ping @nattfodd

**Comment by GildedHonour** [comment]
It has to do with a way it's been built. If a `libvips` version has been built without PDF support, one should rebuild it and the issue should become resolved.

With PDF support it'll look like this:

```
vips -l pdfload
          VipsForeignLoadPdfFile (pdfload), load PDF with libpoppler (.pdf), priority=0, is_a, get_flags, get_flags_filename, header, load
```

**Comment by barockok** [comment]
@blackpond @akashkinwad, it relates to the `libvips` build, just like @GildedHonour said. 

If you update to despeck `0.5.0` it'll detect whether your libvips support pdf or not. make sure you have either PDFium or poppler-glib installed before you build/install libvips.

![image](https://user-images.githubusercontent.com/474500/93231825-5e2da100-f7a3-11ea-87ea-d77882def76f.png)

**Comment by ronaldtse** [comment]
Thanks @GildedHonour and @barockok ! Closing for now.

**Comment by ronaldtse** [comment]
@barockok can you add the content of "make sure you have either PDFium or poppler-glib installed before you build/install libvips" to the README install steps? Thanks.
