### ISSUE TITLE
Installation error using gem

### ISSUE THREAD

**Issue by diamondraras** [riboseinc/despeck#42]
I have the following error when installing despeck with `gem install despeck`

Traceback (most recent call last):
	12: from /usr/local/bin/despeck:23:in `<main>'
	11: from /usr/local/bin/despeck:23:in `load'
	10: from /var/lib/gems/2.5.0/gems/despeck-0.5.0/exe/despeck:5:in `<top (required)>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /var/lib/gems/2.5.0/gems/despeck-0.5.0/lib/despeck.rb:7:in `<top (required)>'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.17/lib/vips.rb:525:in `<top (required)>'
	 3: from /var/lib/gems/2.5.0/gems/ruby-vips-2.0.17/lib/vips.rb:528:in `<module:Vips>'
	 2: from /var/lib/gems/2.5.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `ffi_lib'
	 1: from /var/lib/gems/2.5.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `map'
/var/lib/gems/2.5.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory

**Comment by ronaldtse** [comment]
@diamondraras did you get to install the libvips library? Are you using macOS?

**Comment by diamondraras** [comment]
@ronaldtse 
i used google colab to install despeck. here is my install script

`
apt install libvips libvips-dev libvips-tools

apt install ruby-dev

sudo apt install libtool libffi-dev ruby ruby-dev make

sudo apt install libzmq3-dev libczmq-dev

gem install ffi-rzmq

gem install specific_install

gem specific_install https://github.com/SciRuby/iruby

apt-get install libmagick++-dev

gem install despeck
`

But the error always appears
Before this script was working and despeck was installed correctly but now the error appears

**Comment by ronaldtse** [comment]
That's very strange. @barockok would you have time to check? Thanks!

**Comment by diamondraras** [comment]
@ronaldtse thanks
